# ===============================
# Application
# ===============================
spring.application.name=distributed-payment-processing


# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/payment_platform
spring.datasource.username=root
spring.datasource.password=innobliss123$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Server
# ===============================
server.port=8099
